version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - database_data:/var/lib/postgresql/database_test/
    ports:
      - "5432:5432"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    container_name: api
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: sh -c "
      alembic upgrade head
      && python3 create_data.py
      && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000"


  minio:
    image: minio/minio:latest
    container_name: s3
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: aimu7OhSh4zei
      MINIO_ROOT_PASSWORD: Maebee0xaeX6ohc
      MINIO_BUCKET: secure-t
    volumes:
      - s3data:/data
    command: server  /data  --console-address ":9090" --address ":9000"


  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 aimu7OhSh4zei Maebee0xaeX6ohc;
      /usr/bin/mc mb myminio/secure-t;
      /usr/bin/mc anonymous set public myminio/secure-t;
      exit 0;
      "
  caddy:
    image: samuraii143/caddy:scorm
    container_name: caddy
    restart: always
    labels:
      - com.secure-t.caddy
    ports:
      - 80:80
      - 443:443
      - 81:81
      - 2019:2019


volumes:
  database_data:
  s3data:
