version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - database_data:/var/lib/postgresql/database_test/
    ports:
      - "5432:5432"

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    container_name: api
    depends_on:
      - db
    ports:
      - "5000:5000"
    command: sh -c "
      alembic upgrade head
      && python3 create_data.py
      && uvicorn main:app --host 0.0.0.0 --port 5000 --reload --no-access-log --use-colors"


volumes:
  database_data:
