"""add file_link field

Revision ID: e2520f55545c
Revises: a7b406aac3b7
Create Date: 2023-05-29 13:33:49.899048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2520f55545c'
down_revision = 'a7b406aac3b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cmi_courses', sa.Column('file_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cmi_courses', 'file_link')
    # ### end Alembic commands ###
